In [1]:
import pandas as pd
from pathlib import Path
import os
from os.path import join as opj
from tqdm.auto import tqdm
import ast
import numpy as np
import re
from collections import Counter

In [2]:
BASE_DIR = os.getcwd()  
PARENT_DIR = os.path.dirname(BASE_DIR)  
DATASET_DIR = os.path.join(PARENT_DIR, "data")

In [3]:
i = 0
# read dataset
shein_data = pd.read_csv(opj(DATASET_DIR, "shein_sample_5000.csv"), sep=";", encoding="ISO-8859-1")
for i in tqdm(list(range(len(shein_data)))):
    desc, images = shein_data.iloc[i][["description", "images"]]
    
    # read description and images info as lists
    desc, images = ast.literal_eval(desc), ast.literal_eval(images)
    shein_data.loc[i, ["description", "images"]] = [desc, images]

  0%|          | 0/5000 [00:00<?, ?it/s]

In [4]:
shein_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   url          5000 non-null   object
 1   name         5000 non-null   object
 2   sku          5000 non-null   object
 3   price        5000 non-null   object
 4   size         4998 non-null   object
 5   brand        2428 non-null   object
 6   description  5000 non-null   object
 7   images       5000 non-null   object
dtypes: object(8)
memory usage: 312.6+ KB

In [5]:
shein_data.head(20)

,url,name,sku,price,size,brand,description,images
0,https://us.shein.com/Flower-Decor-Face-Coverin...,Flower Decor Face Covering Chain,SKU: sc2302055742295937,$2.50,one-size,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",[https://storage.yandexcloud.net/clothes-and-w...
1,https://us.shein.com/Lace-Up-Bodycon-Skirt-p-7...,Lace Up Bodycon Skirt,SKU: sw2111151588254852,$7.25,"XS(2),S(4),M(6),L(8/10)",NaN,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt...",[https://storage.yandexcloud.net/clothes-and-w...
2,https://us.shein.com/High-Waist-Twist-Front-Sh...,High Waist Twist Front Shorts,SKU: sw2211215551435599,$8.99,"S(4),M(6),L(8/10),XL(12)",NaN,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},...",[https://storage.yandexcloud.net/clothes-and-w...
3,https://us.shein.com/ROMWE-Sweetness-Cherry-La...,ROMWE Sweetness Cherry Lace Cami Top,SKU: rw2203161166248409,$7.00,"XS(2),S(4),M(6),L(8/10),XL(12),XXL(14)",ROMWE,"[{'Color': 'Red and White'}, {'Style': 'Casual...",[https://storage.yandexcloud.net/clothes-and-w...
4,https://us.shein.com/Cut-Out-Criss-Cross-One-P...,Cut Out Criss Cross One Piece Swimsuit,SKU: sw2108269195581516,$9.50,"S(4),M(6),L(8/12)",NaN,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant...",[https://storage.yandexcloud.net/clothes-and-w...
5,https://us.shein.com/Tie-Backless-Halter-Trian...,Tie Backless Halter Triangle V-string Bikini S...,SKU: sw2211254128128287,$10.49,"S(4),M(6),L(8/12)",NaN,"[{'Color': 'White'}, {'Pattern Type': 'Plain'}...",[https://storage.yandexcloud.net/clothes-and-w...
6,https://us.shein.com/Solid-Tie-Side-Cover-Up-S...,Solid Tie Side Cover Up Skirt,SKU: sw2202158913200151,$4.49,one-size,NaN,"[{'Color': 'Black'}, {'Pattern Type': 'Plain'}...",[https://storage.yandexcloud.net/clothes-and-w...
7,https://us.shein.com/ROMWE-PUNK-Tie-Dye-Letter...,ROMWE PUNK Tie Dye & Letter Graphic Notched Ne...,SKU: sw2205252404438114,$6.99,"XS(2),S(4),M(6),L(8/10)",ROMWE,"[{'Color': 'Brown'}, {'Style': 'Casual'}, {'Pa...",[https://storage.yandexcloud.net/clothes-and-w...
8,https://us.shein.com/O-ring-Detail-Halter-Knot...,O-ring Detail Halter Knot Side Triangle Thong ...,SKU: sw2202159072898493,$11.49,"S(4),M(6),L(8/12),XL(14)",NaN,"[{'Color': 'Mocha Brown'}, {'Style': 'Sexy'}, ...",[https://storage.yandexcloud.net/clothes-and-w...
9,https://us.shein.com/Bow-Bead-Decor-Face-Cover...,Bow & Bead Decor Face Covering Chain,SKU: sc2302052787833869,$2.80,one-size,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",[https://storage.yandexcloud.net/clothes-and-w...
10,https://us.shein.com/SHEIN-ICON-Buckle-Tape-Cu...,SHEIN ICON Buckle Tape Cut Out Lace Up Bootcut...,SKU: sw2203020080891966,$8.00,"XS(2),S(4),M(6),L(8/10)",SHEIN ICON,"[{'Color': 'Army Green'}, {'Style': 'Sexy'}, {...",[https://storage.yandexcloud.net/clothes-and-w...
11,https://us.shein.com/ROMWE-PUNK-Grunge-High-Wa...,ROMWE PUNK Grunge High Waist Floral & Baroque ...,SKU: sw2208033120692623,$8.00,"XS(2),S(4),M(6),L(8/10)",ROMWE,"[{'Color': 'Multicolor'}, {'Style': 'Casual'},...",[https://storage.yandexcloud.net/clothes-and-w...
12,https://us.shein.com/Paperbag-Waist-Wide-Leg-P...,Paperbag Waist Wide Leg Pants,SKU: sw2211288977857662,$14.49,"XS(2),S(4),M(6),L(8/10)",NaN,"[{'Color': 'Black'}, {'Style': 'Casual'}, {'Pa...",[https://storage.yandexcloud.net/clothes-and-w...
13,https://us.shein.com/Contrast-Mesh-Cut-Out-Hal...,Contrast Mesh Cut Out Halter One Piece Swimsuit,SKU: sw2210214024428244,$12.49,"S(4),M(6),L(8/12),XL(14),0XL-4XL",NaN,"[{'Color': 'Black'}, {'Pattern Type': 'Plain'}...",[https://storage.yandexcloud.net/clothes-and-w...
14,https://us.shein.com/Color-Block-Triangle-Thon...,Color Block Triangle Thong Bikini Swimsuit,SKU: swswim23210402674,$11.49,"S(4),M(6),L(8/12)",NaN,"[{'Color': 'Royal Blue'}, {'Style': 'Sexy'}, {...",[https://storage.yandexcloud.net/clothes-and-w...
15,https://us.shein.com/Split-Thigh-Cover-Up-p-29...,Split Thigh Cover Up,SKU: swcover25210618208,$13.49,"one-size,0XL-4XL",NaN,"[{'Color': 'Navy Blue'}, {'Neckline': 'Scoop N...",[https://storage.yandexcloud.net/clothes-and-w...
16,https://us.shein.com/ROMWE-Eyelet-Embroidery-C...,ROMWE Eyelet Embroidery Cami,SKU: ri2205139888519824,$4.50,"S(4),M(6),L(8/10)",ROMWE,"[{'Color': 'White'}, {'Style': 'Boho'}, {'Patt...",[https://storage.yandexcloud.net/clothes-and-w...
17,https://us.shein.com/Bikinx-Rib-Triangle-High-...,Bikinx Rib Triangle High Cut Bikini Swimsuit,SKU: sw2209131606885251,$10.49,"XS,S,M,L",Bikinx,"[{'Color': 'Teal Blue'}, {'Style': 'Sexy'}, {'...",[https://storage.yandexcloud.net/clothes-and-w...
18,https://us.shein.com/ROMWE-Kawaii-Bow-Decor-Fa...,ROMWE Kawaii Bow Decor Face Covering,SKU: rc2207210016628545,$2.10,one-size,ROMWE,"[{'Color': 'Pink'}, {'Material': 'Fiber'}, {'P...",[https://storage.yandexcloud.net/clothes-and-w...
19,https://us.shein.com/SHEIN-Slant-Pocket-Belted...,SHEIN Slant Pocket Belted PU Leather Pants,SKU: sw2106190446101160,$10.25,"XS(2),S(4),M(6),L(8/10)",NaN,"[{'Color': 'Rust Brown'}, {'Style': 'Party'}, ...",[https://storage.yandexcloud.net/clothes-and-w...

In [6]:
#dropping unwanted columns
shein_data = shein_data.drop(columns=['url'])

In [7]:
shein_data.head()

,name,sku,price,size,brand,description,images
0,Flower Decor Face Covering Chain,SKU: sc2302055742295937,$2.50,one-size,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",[https://storage.yandexcloud.net/clothes-and-w...
1,Lace Up Bodycon Skirt,SKU: sw2111151588254852,$7.25,"XS(2),S(4),M(6),L(8/10)",NaN,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt...",[https://storage.yandexcloud.net/clothes-and-w...
2,High Waist Twist Front Shorts,SKU: sw2211215551435599,$8.99,"S(4),M(6),L(8/10),XL(12)",NaN,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},...",[https://storage.yandexcloud.net/clothes-and-w...
3,ROMWE Sweetness Cherry Lace Cami Top,SKU: rw2203161166248409,$7.00,"XS(2),S(4),M(6),L(8/10),XL(12),XXL(14)",ROMWE,"[{'Color': 'Red and White'}, {'Style': 'Casual...",[https://storage.yandexcloud.net/clothes-and-w...
4,Cut Out Criss Cross One Piece Swimsuit,SKU: sw2108269195581516,$9.50,"S(4),M(6),L(8/12)",NaN,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant...",[https://storage.yandexcloud.net/clothes-and-w...

In [8]:
#finding all of the brand names
shein_data['brand'].unique().tolist()

['QingSang\xa0Accessories Apparel Accessories',
 nan,
 'ROMWE',
 'SHEIN ICON',
 'Bikinx',
 'DAZY',
 'SHEIN SXY',
 'DiFanYa Apparel Accessories',
 'YouyueSportsGoodsFactory Apparel Accessories',
 'SHEIN EZwear',
 'SHEIN X VICTOR VON SCHWARZ',
 'SHEIN X Kovid Kapoor',
 'SHEIN X VOON',
 'SHEIN X EMILY REED',
 'SHEIN Frenchy',
 'EMERY ROSE',
 'SHEIN BAE',
 'DANDING Apparel Accessories',
 'SHEIN BIZwear',
 'SHEIN X Cecile Betbeze',
 'SHEIN VCAY',
 'Bazun',
 'MOTF',
 'SHEIN Unity',
 'Zhanyan Apparel Accessories',
 'SHEIN X VALHALLA',
 'SHEIN X No?-Liam',
 'SHEIN X Lindsey Kate',
 'SHEIN Modely',
 'SHEIN X (in)SALT-Y(d)',
 'YHOLF Apparel Accessories',
 'InnNew Apparel Accessories',
 'Xinshi Apparel Accessories',
 'Yuxiang Apparel Accessories',
 'SHEIN X Firefall',
 'SHEIN X Sayndo',
 'Meanbeauty',
 'SHEIN X VERO DIAZ',
 'Baozhining Apparel Accessories',
 'SHEIN BASICS',
 'SHEINNeu',
 'SHEIN Tall',
 'Jhdxjwmy',
 'Double Crazy',
 'SHEIN X GottaBeJelly',
 'evoluSHEIN',
 'SHEIN X BAW Collection',
 'YUM Apparel Accessories',
 'Motosozai',
 'SHEIN X CLOUD BY CLAU',
 'RUIMSOCKS Underwear & Sleepwear&Apparel Accessories',
 'SHEIN X GD GRL BHVIOR',
 'SHEIN X Huberlene',
 'SHEIN X LORI STEPHENSON',
 'SHEIN X EBIB',
 'SHEIN X Eva Novielli',
 'SHEIN X Manic Pop',
 'SHEIN X Gabriella Mavri',
 'SHEIN X Michelle Wong',
 'SHEIN X Sara Cennamo',
 'Sleepywalk Apparel Accessories',
 'SHEIN MOD',
 'SHEIN X GOD.like',
 'SHEIN X CIRCE',
 'SHEIN X Isabelle WANG',
 'SHEIN X ANIHOUVI Ludmilla',
 'SHEIN X GAUTII',
 'SHEIN X Maria',
 'SHEIN X Season Lye',
 'SHEIN X SAAMU',
 'SHEIN PETITE',
 'FFSHIPIN Apparel Accessories',
 'SHEIN X Vibrant Dames',
 'Xinyao Apparel Accessories',
 'Xinlei Apparel Accessories',
 'Pairui',
 'Jxhyy Apparel Accessories',
 'SHEIN X Abrar Zenkawi',
 'SHEIN X Peartree Stories',
 'OUZHIYA Apparel Accessories',
 'SHEIN X My0812retro Streetwear',
 'SHEIN X DIANA MAHA',
 'SHEIN X Meng Fei Lin',
 'Simple Retro',
 'SHEIN X Israel Jasso',
 'SHEIN X Glitzy',
 'SHEIN X Valerie Hsin',
 'SHEIN X Danielle Monae',
 "SHEIN X Geegee's Shop",
 'SHEIN X Raluk',
 'SHEIN X PANCHO',
 'SHEIN X OSHEN',
 'SHEIN X New Little Wings',
 'SHEIN X Kasey Nease',
 'SHEIN X Rossella Logiurato',
 'SHEIN X Ashley D Love',
 'SHEIN X YUPING',
 'SHEIN X Five Karats',
 'SHEIN X WANDERFUL',
 'SHEIN X Sarah Stevenson',
 'SHEIN X Becci',
 'SHEIN X QIN LIN',
 'SHEIN X DESIGNS BY ZAHMAR',
 'SHEIN X MAYSOPHIE',
 'SHEIN X MY-DOLLS',
 'QijiHairDecorationHouse',
 'SHEIN X Delapaz',
 'SHEIN X LENG CHIN',
 'SHEIN X Aninho',
 'SHEIN X Bronze Empire',
 'SHEIN X PAOLA DINAZARETH',
 "SHEIN X L'Amour Morbide",
 'SHEIN X Kaotip',
 'SHEIN X NATALIA DEDIOS',
 'SHEIN X Lilee',
 'SHEIN X TZC',
 'Louis Apparel Accessories',
 'SHEIN X KARISSA SCHNEIDER',
 'SHEIN X Oxana',
 'SHEIN X LRUBRE',
 'SHEIN X NICOLE CANDELORO',
 'SHEIN X RAUL OROZCO',
 'SHEIN X RAYA',
 'SHEIN X TIYA',
 'SHEIN X L\x92Mane',
 'SHEIN X CAROLINE 1942',
 'SHEIN X Ashi',
 'SHEIN X Diana Brettas',
 'SHEIN X DORY YOUHANA',
 'SHEIN X Scube',
 'SHEIN X Janie Hao',
 'SHEIN X Bethany Grace',
 'SHEIN X Areej Rimawi',
 'SHEIN X Ishara Gamage',
 'SHEIN X Kitty & Rhodes',
 'SHEIN X DAY LITE',
 'SHEIN X REN by Lau',
 'SHEIN X FLO PONCE PRINTS',
 'SHEIN X Weims',
 'SHEIN X ISABELLA',
 'Knit Mix',
 'SHEIN X NAOMI',
 'SHEIN X Yilang',
 'SHEIN X Renakok',
 'SHEIN X C-Era',
 'SHEIN X Laysia Lavon',
 'SHEIN X VNCIRCLE',
 'SHEIN X The Pearl Collective',
 'SHEIN X Federica',
 'SHEIN X Channa Karasi',
 'SHEIN X Temmie TT',
 'SHEIN X LIYUN X',
 'SHEIN X Carlotta Cardillo',
 'SHEIN X ASSIA PESENTI',
 'SHEIN X Afaf',
 'SHEIN X Cute but Psycho',
 'SHEIN X FORTUNATE',
 'SHEIN X TRANG DUONG',
 'SHEIN X MINA',
 'SHEIN X Nayeli Lazaro',
 'SHEIN X FLOR BY LO',
 'SHEIN X House of Fleek',
 'SHEIN X Sergio Ricchitelli',
 'DEARCASE',
 'SHEIN X IMperfect',
 'SHEIN X Tainted Love',
 'SHEIN X Mithra',
 'SHEIN X NOOR BREICH',
 'SHEIN X CRYBABY',
 'SHEIN X D_3H30',
 'SHEIN X TWINKLE CAT',
 'SHEIN X RAQUEL',
 'SHEIN X MEGAN JOHNSON',
 'SHEIN X Adrienne Alexis',
 'SHEIN X K Chirinos',
 'SHEIN X TSUN SHUIN',
 'SHEIN X KaylaProductions',
 'SHEIN X Sabrine',
 'SHEIN X Nikole Sanches',
 'SHEIN X JESSE G',
 'SHEIN X CakeSpy',
 'SHEIN X Valeria Lujan',
 'SHEIN X Andrea St.',
 'SHEIN X DINA STARS',
 'SHEIN X Nkao Hle Hang',
 'SHEIN X Pylog',
 'SHEIN X KES',
 'SHEIN X Reanne Wang',
 'SHEIN X NAJILARAQUELDESIGNS',
 'SHEIN X MPDC',
 'SHEIN X In Moraine',
 'SHEIN X Manufactured Gold',
 'SHEIN X TAII Bangkok',
 'SHEIN Belle',
 'SHEIN X Felicity',
 'SHEIN X Shwetha Anand Designs',
 'SHEIN X Felicis',
 'SHEIN X Lillian Butterworth',
 'SHEIN X INSIGNIA',
 'SHEIN X Madina',
 'SHEIN X Sara Mezzanotti',
 'SHEIN X Smita Shrinivas',
 'SHEIN X VAE',
 'SHEIN X FREAK CITY',
 'SHEIN X Catia Bart',
 'SHEIN X ARUS',
 'D&M',
 'SHEIN X Krystal Everdeen',
 'SHEIN X Creative Calm',
 'SHEIN X NJH Design',
 'SHEIN X Juliana Jace',
 'SHEIN X CAMILLE JUGE',
 'SHEIN X Cayetano',
 'SHEIN X EclecticCollection',
 'Apperloth A',
 'SHEIN X CARSON WONG',
 'SHEIN X Brydie Rae Farrell',
 'SHEIN X Kirsten Claire',
 'SHEIN X MEL ROUMEC',
 'Shein x Jeanelle Sonia',
 'SHEIN X Xosefino',
 'SHEIN X Michaela Eddington',
 'SHEIN X M.E.L.T',
 'SHEIN X CHERYL TEO',
 'SHEIN X MAR?A PONCE',
 'SHEIN X Gulnara Gulia',
 'SHEIN X REVELIGION',
 'SHEIN X KYS',
 'SHEIN X DESIGNED BY TONY',
 'SHEIN X Jennty Designs',
 'SHEIN X The Perfect Party',
 'SHEIN X SQUID HOUSE',
 'SHEIN X Eva Ruiz',
 'SHEIN X Provocation',
 'SHEIN X JEWEL SUM',
 'SHEIN X MIYUKI',
 'SHEIN X Neon Island',
 'SHEIN X Sean Betco',
 'SHEIN X Safari',
 'SHEIN X Cute-Saint',
 'SHEIN X CRIZM',
 'SHEIN X KAY',
 'SHEIN X RECKLESS ERICKA',
 'SHEIN X ALEXANDER KURMANIN',
 'SHEIN X JuliaSasakiHernanz',
 'Sollinarry',
 'SHEIN X Drea',
 'SHEIN X Delayne Dixon',
 'SHEIN X By Nusha',
 'SHEIN X KierraNichole',
 'SHEIN X XIAO YAOQIUZI',
 'SHEIN X AMA',
 'SHEIN X Hanchi',
 'SHEIN X LILI PAN',
 'SHEIN X GEANINA',
 'SHEIN X Naomi Jasmin',
 'SHEIN X Chiara',
 'SHEIN X Dulc?',
 'SHEIN X TANIA ORELLANA',
 'SHEIN X Rituales',
 'SHEIN X ROCIO',
 'SHEIN X Zizzari',
 'SHEIN X Sylvia Mollie',
 'SHEIN X Jessica Di Michele',
 'SHEIN X Adiva Marie Co.',
 'SHEIN X Xenia',
 'SHEIN X YEARS',
 'SHEIN X Bea Araza',
 'SHEIN X Zoe Foreman',
 'SHEIN X SonofTheSunStudio',
 'SHEIN X Eun',
 'SHEIN X Claire-Lys',
 'LOVE&LEMONADE',
 'SHEIN X Nora Ink',
 'SHEIN X Alice Wanderland',
 'MEYSI KIM',
 'SHEIN X Shahedah',
 'SHEIN X Innovante',
 'SHEIN X PHOZOHO',
 'SHEIN X Pchawj',
 'SHEIN X LI WEN',
 'SHEIN X Royal Daisy',
 'SHEIN X ICW',
 'SHEIN X PANUCO',
 'SHEIN X ARTH',
 'SHEIN X Attilio De Angelis',
 'SHEIN X PAMELA',
 'SHEIN X SOBOSS BRAND',
 'SHEIN X ABIMER',
 'SHEIN X Anne Kyrsten',
 'SHEIN X Kesha Alein',
 'SHEIN X Veronica Mancini',
 'SHEIN X BLENX CODE',
 'SHEIN X Aini Yang',
 "SHEIN X Jad'e by Jas Thomas",
 'SHEIN X Yelly Gray',
 'SHEIN X Sogna',
 'SHEIN X NM3',
 'SHEIN X GIISE',
 'SHEIN X Let Them Stare',
 'SHEIN X Sire Leo Lamar',
 'SHEIN X FAYE CHAN',
 'SHEIN X Leslie Samano',
 'SHEIN X Tina Benally Art',
 'SHEIN X Anke Wonder',
 'SHEIN X CLOSET EXCLUSIVES',
 'SHEIN X MIKYLIE',
 'SHEIN X Farah Wali',
 'SHEIN X AZNE',
 'SHEIN X Spagnelli',
 'SHEIN X RITA H',
 'SHEIN X Mountain Vintage Press',
 'SHEIN X Basse Couture',
 'SHEIN X Alexandra Five',
 'SHEIN X ARIA',
 'SHEIN X TheBoxMethod',
 'SHEIN X Larissa torres',
 'SHEIN X YELLOW MUSHMELLOW',
 'SHEIN X Redefinition',
 'SHEIN X PAULINE MURATI',
 'SHEIN X RL',
 'SHEIN X STEFANONI STUDIO',
 'SHEIN X MEC Wasa',
 'SHEIN X SARI',
 'SHEIN X X52X',
 'SHEIN X SMYLE',
 'SHEIN X LUSINE BONFIELD',
 'SHEIN X Lazy Hoya',
 'SHEIN X Jojee Apparel',
 'SHEIN X SABOTAGE 2C5F',
 'SHEIN X VB Collection',
 'SHEIN X New Romance',
 'SHEIN X DEATH BY DOLLS',
 'SHEIN X VALERIA G?MEZ',
 'SHEIN X Andra Popovici',
 'SHEIN X AMOF',
 'SHEIN X Rebecca Silva',
 'SHEIN X Chompoohbua',
 'SHEIN X ppmid',
 'SHEIN X RAGLESS',
 'SHEIN X TATYANA',
 'SHEIN X YINNG',
 'SHEIN X Shanika Marie',
 'SHEIN X Shelby',
 'BTFBM',
 'SHEIN X REESEDELUCA',
 'SHEIN X Liliana Luna',
 'SHEIN X D.A.Z.H.E',
 'SHEIN X YAYA ZAHIR',
 'SHEIN X Lezio Lopes',
 'SHEIN X NINACIA',
 'SHEIN X MOMI-KO']

In [9]:
#suspecting NaN values in the brand column are from the regular line
brands_to_find = ['shein', 'SheIn', 'SHEIN','She In', 'she in', 'SHE IN']
found = shein_data['brand'].isin(brands_to_find).any()
print(found)

False

In [10]:
#replacing NaN values with SHEIN in the brand column and checking
shein_data['brand'] = shein_data['brand'].replace(np.nan, 'SHEIN')
brands_to_find = ['SHEIN']
found = shein_data['brand'].isin(brands_to_find).any()
print(found)

True

In [11]:
#changing price column to a float 
shein_data['price'] = shein_data['price'].str.replace('$', '', regex=False)
shein_data['price'] = pd.to_numeric(shein_data['price'], errors='coerce')
shein_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         5000 non-null   object
 1   sku          5000 non-null   object
 2   price        4999 non-null   float64
 3   size         4998 non-null   object
 4   brand        5000 non-null   object
 5   description  5000 non-null   object
 6   images       5000 non-null   object
dtypes: float64(1), object(6)
memory usage: 273.6+ KB

In [12]:
#investigating name column
print(shein_data['name'].head(100).to_list())

['Flower Decor Face Covering Chain', 'Lace Up Bodycon Skirt', 'High Waist Twist Front Shorts', 'ROMWE Sweetness Cherry Lace Cami Top', 'Cut Out Criss Cross One Piece Swimsuit', 'Tie Backless Halter Triangle V-string Bikini Swimsuit', 'Solid Tie Side Cover Up Skirt', 'ROMWE PUNK Tie Dye & Letter Graphic Notched Neck Bell Sleeve Crop Tee', 'O-ring Detail Halter Knot Side Triangle Thong Bikini Swimsuit', 'Bow & Bead Decor Face Covering Chain', 'SHEIN ICON Buckle Tape Cut Out Lace Up Bootcut Pants', 'ROMWE PUNK Grunge High Waist Floral & Baroque Print Lettuce Trim Skirt', 'Paperbag Waist Wide Leg Pants', 'Contrast Mesh Cut Out Halter One Piece Swimsuit', 'Color Block Triangle Thong Bikini Swimsuit', 'Split Thigh Cover Up', 'ROMWE Eyelet Embroidery Cami', 'Bikinx Rib Triangle High Cut Bikini Swimsuit', 'ROMWE Kawaii Bow Decor Face Covering', 'SHEIN Slant Pocket Belted PU Leather Pants', 'Geo Print Wide Waistband Biker Shorts', 'ROMWE Fairycore Drawstring Waist Tartan Skirt', 'Glitter Lace Up Plunging One Piece Swimsuit', 'Hollow Out Cover Up Dress', 'ROMWE PUNK Letter Graphic Crop Tee', 'Bikinx Floral Print Triangle Bikini Swimsuit', '3pack Dalmatian Triangle Bikini Swimsuit & Cover Up', 'Star Decor Face Covering Chain', 'SHEIN Mulvari Lace Up 2 In 1 Pants', 'DAZY High Waist Pleated Hem Skirt', 'ROMWE Sweetness Floral Lace Cami Top', 'Split Thigh Cover Up Dress', 'Faux Pearl Decor Knot Side Sheer Cover Up Skirt Without Bikini', 'ROMWE Floral Appliques Lace Cami Top', 'Plant Print Tie Side Bikini Swimsuit', 'Heart Decor Face Covering Chain', 'Drawstring Waist Tie Back Pants', 'DAZY High Waist Split Thigh Skirt', 'ROMWE Skull Print Tank Top', 'Leopard Criss Cross One Piece Swimsuit', 'Eyelet Embroidery Pompom Cover Up', 'ROMWE Jacquard Ruffle Hem Appliques Cami', 'Halter Triangle Tie Side Bikini Swimsuit', 'Butterfly Decor Face Covering Chain', 'SHEIN SXY Lace Up High Waist Skirt', 'Patch Pocket Push Buckle Belted Wind Joggers', 'ROMWE PUNK Reflective Skeleton Print Crop Tee & Biker Shorts', 'Striped Triangle Bikini Swimsuit', 'Colorblock Wrap Bikini Swimsuit', 'Plain Drawstring Cover Up Dress', 'SHEIN EZwear Wings Pattern Short Sleeve Tee', 'Smocked Triangle Bikini Swimsuit With Beach Skirt', '3pack Halter Triangle Bikini Swimsuit & Geo Print Kimono', 'Solid Face Covering', 'SHEIN High Waist Sequin Flare Leg Pants', 'Cut Out Lace Insert Biker Shorts', 'ROMWE Fairycore Floral Embroidery Lace Up Cami Top', 'Bikinx Floral Cut Out Criss Cross One Piece Swimsuit', 'Shirred Ruffle Hem Bandeau Cover Up', 'ROMWE Appliques Ribbed Halter Top', 'Floral Print Smocked Halter Bikini Swimsuit', 'Bow Decor Face Covering Chain', 'Ruffle Hem Wide Leg Shorts', 'High Waist Zip Side Ruffle Trim Skort', 'ROMWE PUNK Drawstring Waist Flap Pocket Wide Leg Parachute Pants', '3pack Plain Criss Cross Halter Bikini Swimsuit & Cover Up Pants', 'Solid Open Front Kimono', 'ROMWE PUNK Grunge Floral & Slogan Graphic Crop Tee', 'Allover Print Halter Triangle Bikini Swimsuit With Cover Up', '3pack Rhinestone Studded Halter Bikini Swimsuit & Beach Skirt', 'Solid Face Covering', 'SHEIN Split Hem Flare Leg Wave Striped Pants', 'Tropical Print Triangle Bikini Swimsuit With Cover Up', 'SHEIN EZwear Letter Graphic Elastic Waist Shorts', 'ROMWE 3pack Solid Bikini Swimsuit With Beach Skirt', 'Marble Print Underwire Push Up One Piece Swimsuit', 'Bikinx Random Floral Sweetheart Neck Cover Up Top Without Bikini', 'ROMWE Floral Pattern Contrast Binding Knit Top', 'Plain Halter Triangle Bikini Swimsuit', 'Cake Decor Face Covering Chain', 'SHEIN X VICTOR VON SCHWARZ Split Hem Flare Leg Pants', 'Swiss Dot Drawstring Side Ruffle Hem Ruched Bodycon Skirt', 'ROMWE STPL Striped Button Crop Cami', 'Criss Cross One Piece Swimsuit', 'Slit Thigh Crochet Cover Up', 'ROMWE PUNK Grunge Floral Print Crop Tee', '3pack Plain Halter Triangle Bikini Swimsuit & Cover Up', 'Solid Face Covering', 'SHEIN Mulvari Elastic Waist Floral Print Wide Leg Pants', 'SHEIN X Kovid Kapoor Graphic Print Split Thigh Skirt', 'ROMWE Street Life Solid Cargo Joggers', 'Textured Crisscross Cut Out One Piece Swimsuit & Sheer Mesh Beach Skirt', 'Textured Halter Triangle Bikini Swimsuit', 'Fishnet overlay Split Cover Up', 'ROMWE X Tiggtactoe Letter Frog Graphic Drop Shoulder Tee', 'Floral Print Halter Bikini Swimsuit', 'Flower Decor Face Covering Chain', 'SHEIN X VOON Slant Pocket Wide Leg Shorts', 'Frill Trim Halter Triangle Tie Side Bikini Swimsuit', 'High Waist Fold Pleated Shorts']

In [13]:
#category function
def assign_category(df, col):

    conditions = [
        shein_data['name'].str.contains('Skirt', case=False, na=False),
        shein_data['name'].str.contains('Dress', case=False, na=False),
        shein_data['name'].str.contains('Shorts', case=False, na=False),
        shein_data['name'].str.contains('skort', case=False, na=False),
        shein_data['name'].str.contains('Top|Cami|Tee', case=False, na=False),
        shein_data['name'].str.contains('Pants|Trousers|Joggers', case=False, na=False),
        shein_data['name'].str.contains('Swimsuit', case=False, na=False),
        shein_data['name'].str.contains('Chain', case=False, na=False),
    ]

    categories = ['Skirt', 'Dress', 'Shorts', 'Skort', 'Top', 'Pants', 'Swimsuit', 'Jewelry']

    shein_data['category'] = np.select(conditions, categories, default='Other')
    return df

In [14]:
#applying the function to create a category
shein_data = assign_category(shein_data, 'name')
shein_data.head()

,name,sku,price,size,brand,description,images,category
0,Flower Decor Face Covering Chain,SKU: sc2302055742295937,2.50,one-size,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",[https://storage.yandexcloud.net/clothes-and-w...,Jewelry
1,Lace Up Bodycon Skirt,SKU: sw2111151588254852,7.25,"XS(2),S(4),M(6),L(8/10)",SHEIN,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt...",[https://storage.yandexcloud.net/clothes-and-w...,Skirt
2,High Waist Twist Front Shorts,SKU: sw2211215551435599,8.99,"S(4),M(6),L(8/10),XL(12)",SHEIN,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},...",[https://storage.yandexcloud.net/clothes-and-w...,Shorts
3,ROMWE Sweetness Cherry Lace Cami Top,SKU: rw2203161166248409,7.00,"XS(2),S(4),M(6),L(8/10),XL(12),XXL(14)",ROMWE,"[{'Color': 'Red and White'}, {'Style': 'Casual...",[https://storage.yandexcloud.net/clothes-and-w...,Top
4,Cut Out Criss Cross One Piece Swimsuit,SKU: sw2108269195581516,9.50,"S(4),M(6),L(8/12)",SHEIN,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant...",[https://storage.yandexcloud.net/clothes-and-w...,Swimsuit

In [15]:
print(shein_data['images'].head(3).to_list())

[['https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/02/06/16756668443ff7011f5eb2c82814c0884603d2947a_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/02/06/1675666836e4bc53f352ed55ad72d102f3c918ec47_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/02/06/16756668385c70273ea378a50508a68de521c6d226_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/02/06/1675666841a31c344ad7169f3fe6ed57c017b171de_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/02/06/1675666843c8b780757e1ea957d597e89eced1f6a5_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/02/06/16756668443ff7011f5eb2c82814c0884603d2947a_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/02/06/1675666836e4bc53f352ed55ad72d102f3c918ec47_thumbnail_600x.webp'], ['https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2021/12/17/163970520541d0365e6ca298cd474dda039344b372_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2021/12/17/1639705198c543732e03a7790132925c7d141bb1a5_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2021/12/17/1639705200627220cd0585b628cbcfb59a3ee70555_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2021/12/17/1639705204a6505df1060f0f559fc87b1aa0f92085_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2021/12/17/163970520541d0365e6ca298cd474dda039344b372_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2021/12/17/16397052078664769ccc959a049dfce96a5778d3dc_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2021/12/17/163970521024b1c4f04f0df5b691f82284cffc8cb8_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2021/12/17/163970520541d0365e6ca298cd474dda039344b372_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2021/12/17/1639705198c543732e03a7790132925c7d141bb1a5_thumbnail_600x.webp'], ['https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/01/10/1673343710e82ef2f6459ca5bf2937e6b4860c9144_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/01/10/1673343712de83c525f485be14deb27b7f4bbe2604_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/01/10/1673343707ac0aedecc81c1d5e5c6e233b80b0a9bf_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/01/10/1673343703049d7a7cea6349a76c4493f0bc775738_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/01/10/16733437055fa3633f22e548c33f9473a4b43254d5_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/01/10/1673343708a4d6310966b49bab957628f5c2fd757c_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/01/10/1673343710e82ef2f6459ca5bf2937e6b4860c9144_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/01/10/1673343710e82ef2f6459ca5bf2937e6b4860c9144_thumbnail_600x.webp', 'https://storage.yandexcloud.net/clothes-and-wildberries/clothes-parsing-dataset/shein/2023/01/10/1673343712de83c525f485be14deb27b7f4bbe2604_thumbnail_600x.webp']]

In [16]:
shein_data['image_count'] = shein_data['images'].apply(len)
shein_data.drop(columns=['images'], inplace = True)#dropping images column
shein_data.head()

,name,sku,price,size,brand,description,category,image_count
0,Flower Decor Face Covering Chain,SKU: sc2302055742295937,2.50,one-size,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",Jewelry,7
1,Lace Up Bodycon Skirt,SKU: sw2111151588254852,7.25,"XS(2),S(4),M(6),L(8/10)",SHEIN,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt...",Skirt,9
2,High Waist Twist Front Shorts,SKU: sw2211215551435599,8.99,"S(4),M(6),L(8/10),XL(12)",SHEIN,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},...",Shorts,9
3,ROMWE Sweetness Cherry Lace Cami Top,SKU: rw2203161166248409,7.00,"XS(2),S(4),M(6),L(8/10),XL(12),XXL(14)",ROMWE,"[{'Color': 'Red and White'}, {'Style': 'Casual...",Top,6
4,Cut Out Criss Cross One Piece Swimsuit,SKU: sw2108269195581516,9.50,"S(4),M(6),L(8/12)",SHEIN,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant...",Swimsuit,10

In [17]:
#exploring - checking if the same product is listed more than once using sku
shein_data['sku'].nunique()

5000

In [18]:
#exploring - checking if the same product is listed more than once using name
shein_data['name'].nunique()

4423

In [19]:
#converting size into a string
shein_data['size'] = shein_data['size'].apply(str)

In [20]:
#creating an additional size column that cleanly displays sizes
def parse_sizes(size_str):
    sizes = size_str.split(',')
    return ','.join([s.split('(')[0] for s in sizes])

shein_data['cleaned_size'] = shein_data['size'].apply(parse_sizes)
shein_data.drop(columns=['size'], inplace=True)
shein_data.rename(columns={'cleaned_size': 'sizes'}, inplace=True)

shein_data.head()

,name,sku,price,brand,description,category,image_count,sizes
0,Flower Decor Face Covering Chain,SKU: sc2302055742295937,2.50,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",Jewelry,7,one-size
1,Lace Up Bodycon Skirt,SKU: sw2111151588254852,7.25,SHEIN,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt...",Skirt,9,"XS,S,M,L"
2,High Waist Twist Front Shorts,SKU: sw2211215551435599,8.99,SHEIN,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},...",Shorts,9,"S,M,L,XL"
3,ROMWE Sweetness Cherry Lace Cami Top,SKU: rw2203161166248409,7.00,ROMWE,"[{'Color': 'Red and White'}, {'Style': 'Casual...",Top,6,"XS,S,M,L,XL,XXL"
4,Cut Out Criss Cross One Piece Swimsuit,SKU: sw2108269195581516,9.50,SHEIN,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant...",Swimsuit,10,"S,M,L"

In [21]:
print(shein_data['description'].head(3).to_list())

[[{'Color': 'Multicolor'}, {'Material': 'PMMA'}], [{'Color': 'Black'}, {'Style': 'Sexy'}, {'Pattern Type': 'Plain'}, {'Details': 'Lace Up, Grommet Eyelet'}, {'Waist Line': 'High Waist'}, {'Length': 'Mini'}, {'Type': 'Bodycon'}, {'Fabric': 'High Stretch'}, {'Material': 'Fabric'}, {'Composition': '95% Polyester, 5% Elastane'}, {'Care Instructions': 'Machine wash or professional dry clean'}, {'Sheer': 'No'}], [{'Color': 'Royal Blue'}, {'Style': 'Casual'}, {'Pattern Type': 'Plain'}, {'Type': 'Straight Leg'}, {'Closure Type': 'Zipper Fly'}, {'Details': 'Twist'}, {'Waist Line': 'Natural'}, {'Length': 'Short'}, {'Fit Type': 'Regular Fit'}, {'Fabric': 'Non-Stretch'}, {'Material': 'Woven Fabric'}, {'Composition': '100% Polyester'}, {'Care Instructions': 'Machine wash, do not dry clean'}, {'Sheer': 'No'}]]

In [22]:
# extracting color
def extract_color(desc):
    if isinstance(desc, list):
        for d in desc:
            if 'Color' in d:
                return d['Color']
    return None

shein_data['color'] = shein_data['description'].apply(extract_color)
shein_data.head()

,name,sku,price,brand,description,category,image_count,sizes,color
0,Flower Decor Face Covering Chain,SKU: sc2302055742295937,2.50,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",Jewelry,7,one-size,Multicolor
1,Lace Up Bodycon Skirt,SKU: sw2111151588254852,7.25,SHEIN,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt...",Skirt,9,"XS,S,M,L",Black
2,High Waist Twist Front Shorts,SKU: sw2211215551435599,8.99,SHEIN,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},...",Shorts,9,"S,M,L,XL",Royal Blue
3,ROMWE Sweetness Cherry Lace Cami Top,SKU: rw2203161166248409,7.00,ROMWE,"[{'Color': 'Red and White'}, {'Style': 'Casual...",Top,6,"XS,S,M,L,XL,XXL",Red and White
4,Cut Out Criss Cross One Piece Swimsuit,SKU: sw2108269195581516,9.50,SHEIN,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant...",Swimsuit,10,"S,M,L",Lilac Purple

In [23]:
#display all the colors
shein_data['color'].unique()

array(['Multicolor', 'Black', 'Royal Blue', 'Red and White',
       'Lilac Purple', 'White', 'Brown', 'Mocha Brown', 'Army Green',
       'Navy Blue', 'Teal Blue', 'Pink', 'Rust Brown', 'Chocolate Brown',
       'Silver', 'Green', 'Khaki', 'Black and White', 'Lime Green',
       'Baby Pink', 'Violet Purple', 'Orange', 'Camel', 'Mint Green',
       'Coffee Brown', 'Apricot', 'Light Grey', 'Dusty Pink', 'Blue',
       'Hot Pink', 'Beige', 'Cadet Blue', 'Olive Green', 'Yellow',
       'Maroon', 'Blue and White', 'Grey', 'Dark Grey', 'Mint Blue',
       'Clear', 'Dark Green', 'Baby Blue', 'Red', 'Rusty Rose',
       'Burgundy', 'Burnt Orange', 'Dusty Blue', 'Gold', 'Coral Orange',
       'Mustard Yellow', 'Champagne', 'Mauve Purple', 'Purple', 'Redwood',
       'Red Violet', 'Medium Wash', 'Watermelon Pink', 'Bronze',
       'Rose Red', 'Ginger', 'Coral Pink', 'Light Wash', 'Dark Wash',
       'Dusty Purple'], dtype=object)

In [24]:
# check missing values
print(shein_data['color'].isnull().sum())

0

In [25]:
#adding color category from sub colors  
def group_colors(color):
    color_groups = {
        'Black': ['Black'],
        'Black and White': ['Black and White'],
        'Red': ['Red', 'Red Violet', 'Burgundy', 'Rose Red', 'Rusty Rose', 'Red and White'],
        'Pink': ['Watermelon Pink', 'Pink', 'Dusty Pink', 'Baby Pink', 'Coral Pink'],
        'Blue': ['Royal Blue', 'Navy Blue', 'Teal Blue', 'Blue', 'Cadet Blue', 'Blue and White', 'Light Wash', 'Dark Wash', 'Medium Wash', 'Dusty Blue'],
        'Yellow': ['Yellow', 'Mustard Yellow'],
        'White': ['White', 'Clear'],
        'Purple': ['Lilac Purple', 'Violet Purple', 'Mauve Purple', 'Purple', 'Dusty Purple'],
        'Green': ['Army Green', 'Green', 'Lime Green', 'Mint Green', 'Olive Green', 'Dark Green'],
        'Brown': ['Brown', 'Mocha Brown', 'Chocolate Brown', 'Rust Brown', 'Coffee Brown', 'Ginger', 'Camel', 'Apricot'],
        'Neautral': ['Beige', 'Khaki'],
        'Grey/Silver': ['Light Grey', 'Silver'],
        'Gold/Champagne': ['Gold', 'Champagne'],
        'Orange': ['Orange', 'Burnt Orange', 'Coral Orange'],
    }

    for group, colors in color_groups.items():
        if color in colors:
            return group
    return 'Multi'

shein_data['color_grouped'] = shein_data['color'].apply(group_colors)
shein_data.rename(columns={'color':'subcolor'}, inplace = True)
shein_data.head()

,name,sku,price,brand,description,category,image_count,sizes,subcolor,color_grouped
0,Flower Decor Face Covering Chain,SKU: sc2302055742295937,2.50,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",Jewelry,7,one-size,Multicolor,Multi
1,Lace Up Bodycon Skirt,SKU: sw2111151588254852,7.25,SHEIN,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt...",Skirt,9,"XS,S,M,L",Black,Black
2,High Waist Twist Front Shorts,SKU: sw2211215551435599,8.99,SHEIN,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},...",Shorts,9,"S,M,L,XL",Royal Blue,Blue
3,ROMWE Sweetness Cherry Lace Cami Top,SKU: rw2203161166248409,7.00,ROMWE,"[{'Color': 'Red and White'}, {'Style': 'Casual...",Top,6,"XS,S,M,L,XL,XXL",Red and White,Red
4,Cut Out Criss Cross One Piece Swimsuit,SKU: sw2108269195581516,9.50,SHEIN,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant...",Swimsuit,10,"S,M,L",Lilac Purple,Purple

In [26]:
def extract_attribute(desc_list, key):
    if isinstance(desc_list, list):
        for d in desc_list:
            if key in d:
                return d[key]
    return None

shein_data['material'] = shein_data['description'].apply(lambda x: extract_attribute(x, 'Material'))
shein_data['composition'] = shein_data['description'].apply(lambda x: extract_attribute(x, 'Composition'))

In [27]:
shein_data.head(10)

,name,sku,price,brand,description,category,image_count,sizes,subcolor,color_grouped,material,composition
0,Flower Decor Face Covering Chain,SKU: sc2302055742295937,2.50,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",Jewelry,7,one-size,Multicolor,Multi,PMMA,None
1,Lace Up Bodycon Skirt,SKU: sw2111151588254852,7.25,SHEIN,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt...",Skirt,9,"XS,S,M,L",Black,Black,Fabric,"95% Polyester, 5% Elastane"
2,High Waist Twist Front Shorts,SKU: sw2211215551435599,8.99,SHEIN,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},...",Shorts,9,"S,M,L,XL",Royal Blue,Blue,Woven Fabric,100% Polyester
3,ROMWE Sweetness Cherry Lace Cami Top,SKU: rw2203161166248409,7.00,ROMWE,"[{'Color': 'Red and White'}, {'Style': 'Casual...",Top,6,"XS,S,M,L,XL,XXL",Red and White,Red,Mesh Fabric,"70% Polyamide, 30% Spandex"
4,Cut Out Criss Cross One Piece Swimsuit,SKU: sw2108269195581516,9.50,SHEIN,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant...",Swimsuit,10,"S,M,L",Lilac Purple,Purple,Fabric,"80% Polyamide, 20% Elastane"
5,Tie Backless Halter Triangle V-string Bikini S...,SKU: sw2211254128128287,10.49,SHEIN,"[{'Color': 'White'}, {'Pattern Type': 'Plain'}...",Swimsuit,7,"S,M,L",White,White,None,None
6,Solid Tie Side Cover Up Skirt,SKU: sw2202158913200151,4.49,SHEIN,"[{'Color': 'Black'}, {'Pattern Type': 'Plain'}...",Skirt,6,one-size,Black,Black,Fabric,"95% Polyester, 5% Elastane"
7,ROMWE PUNK Tie Dye & Letter Graphic Notched Ne...,SKU: sw2205252404438114,6.99,ROMWE,"[{'Color': 'Brown'}, {'Style': 'Casual'}, {'Pa...",Top,9,"XS,S,M,L",Brown,Brown,Fabric,100% Polyester
8,O-ring Detail Halter Knot Side Triangle Thong ...,SKU: sw2202159072898493,11.49,SHEIN,"[{'Color': 'Mocha Brown'}, {'Style': 'Sexy'}, ...",Swimsuit,10,"S,M,L,XL",Mocha Brown,Brown,None,None
9,Bow & Bead Decor Face Covering Chain,SKU: sc2302052787833869,2.80,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",Jewelry,7,one-size,Multicolor,Multi,PMMA,None

In [28]:
shein_data['material'].unique()

array(['PMMA', 'Fabric', 'Woven Fabric', 'Mesh Fabric', None,
       'Knitted Fabric', 'Fiber', 'PU Leather', 'Worsted', 'Lace',
       'Polyester', 'Sequins', 'Rib knit', 'Flannelette', 'Plastic',
       'Copper', 'Corduroy', 'Denim', 'Satin', 'Chiffon', 'Glass',
       'Tweed', 'Non-woven Fabric', 'Iron', 'Acrylic', 'Metallic',
       'Suedette', 'Synthetic Fiber', 'Zinc Alloy', 'Polymer Clay',
       'Copper Alloy', 'Linen', 'Polyresin', 'ABS', 'Stainless Steel',
       'Glitter', 'Wool-Like Fabric', 'Artificial Crystal', 'Iron Alloy',
       'Elastane', 'Polyamide', 'Mohair', 'Silk', 'Natural Crystal',
       'Flocking', 'Shell', 'Silicone', 'Embroidery', 'Paper'],
      dtype=object)

In [29]:
shein_data['composition'].unique()

array([None, '95% Polyester, 5% Elastane', '100% Polyester',
       '70% Polyamide, 30% Spandex', '80% Polyamide, 20% Elastane',
       '91% Polyester, 9% Elastane', '60% Viscose, 40% Polyester',
       '82% Polyester, 18% Elastane', '100% Acrylic',
       '94% Viscose, 6% Elastane', '94% Polyester, 6% Elastane',
       '95% Polyester, 5% Spandex', '82% Polyester, 18% Spandex',
       '100% Viscose', '97% Polyester, 3% Elastane',
       '94% Polyester, 6% Spandex', '92% Polyester, 8% Spandex',
       '93% Polyester, 7% Elastane', '100% Polyamide',
       '80% Polyester, 20% Viscose',
       '50% Rayon, 45% Polyester, 5% Elastane',
       '65% Viscose, 35% Polyester',
       '77% Polyester, 16% Viscose, 7% Elastane',
       '92% Polyamide, 8% Elastane', '100% Cotton',
       '80% Nylon, 20% Elastane',
       '62% Polyester, 33% Cotton, 5% Elastane', '65% Nylon, 35% Rayon',
       '96% Polyester, 4% Elastane', '97% Polyester, 3% Spandex',
       '50% Viscose, 28% Nylon, 22% Polyester', '100% Metal',
       '72% Polyester, 28% Cotton', '89% Polyester, 11% Elastane',
       '98% Polyester, 2% Elastane', '92% Polyester, 8% Elastane',
       '100% Rayon', '80% Polyester, 15% Viscose, 5% Elastane',
       '66% Cotton, 30% Polyester, 2% Spandex, 2% Viscose',
       '50% Polyester, 50% Polyurethane', '95% Cotton, 5% Elastane',
       '82% Polyamide, 18% Elastane',
       '79% Polyester, 18% Viscose, 3% Elastane',
       '50% Viscose, 30% Polyester, 20% Nylon',
       '94.1% Polyester, 5.9% Spandex', '90% Polyester, 10% Elastane',
       '90% Viscose, 10% Polyester', '85% Viscose, 15% Linen',
       '75% Polyester, 23% Viscose, 2% Wool',
       '50% Viscose, 28% Polyester, 22% Nylon',
       '67% Polypropylene, 33% Polyester', '93% Viscose, 7% Elastane',
       '52% Polyester, 48% Viscose',
       '67% Polyester, 30% Viscose, 3% Elastane',
       '95% Polyamide, 5% Elastane', '70% Viscose, 30% Nylon',
       '93.5% Polyester, 6.5% Elastane', '95.0% Polyamide, 5.0% Elastane',
       '50% Polyurethane, 45% Polyester, 5% Elastane',
       '49% Viscose, 28% Polyester, 23% Polyamide',
       '50% Viscose, 28% Polyester, 22% Polyamide',
       '87% Polyamide, 13% Elastane', '83% Polyester, 17% Elastane',
       '55% Polyurethane, 45% Polyester',
       '50% Acrylic, 28% Polyester, 22% Polyamide',
       '80% Viscose, 20% Polyamide', '94.1% Polyester, 5.9% Elastane',
       '97% Polyester, 3% Silk',
       '50.2% Rayon, 31.5% Polyester, 18.3% Polyamide',
       '83% Polyester, 11% Viscose, 6% Elastane',
       '80% Polyester, 20% Elastane', '90% Polyamide, 10% Elastane',
       '60% Polyester, 40% Viscose', '81% Viscose, 19% Linen',
       '85% Polyamide, 15% Elastane', '50% Acrylic, 50% Wool',
       '70% Polyester, 25% Viscose, 5% Elastane',
       '67% Polyester, 33% Rayon', '65% Polyamide, 35% Viscose',
       '52% Acrylic, 28% Nylon, 20% Polyester',
       '64% Polyester, 33% Viscose, 3% Elastane',
       '68% Viscose, 23% Polyester, 9% Nylon',
       '62% Polyester, 33% Viscose, 5% Elastane',
       '70% Cotton, 28% Polyester, 2% Elastane',
       '69% Viscose, 26% Polyamide, 5% Spandex',
       '62% Polyester, 34% Viscose, 4% Elastane',
       '65% Viscose, 30% Polyamide, 5% Elastane',
       '74% Viscose, 26% Linen', '63% Polyester, 37% Cotton',
       '88% Polyester, 12% Elastane', '85% Polyester, 15% Elastane',
       '80% Nylon, 20% Spandex',
       '78% Polyester, 20% Viscose, 2% Elastane', '100% Spandex',
       '100% Polyurethane', '65% Rayon, 30% Polyester, 5% Elastane',
       '94% Polyamide, 4% Metallized Fibres, 2% Elastane',
       '93% Polyester, 7% Spandex',
       '80% Polyester, 16% Viscose, 4% Elastane',
       '64% Polyester, 34% Cotton, 2% Elastane',
       '70% Viscose, 30% Lyocell', '89% Silk, 11% Spandex',
       '59% Polyamide, 41% Polyester',
       '60% Polyamide, 30% Viscose, 10% Elastane',
       '72% Polyester, 28% Nylon',
       '68% Polyester, 28% Viscose, 4% Elastane',
       '60% Acrylic, 40% Polyester', '70% Polyester, 30% Acrylic',
       '80.6% Viscose, 19.4% Polyester', '55% Linen, 45% Cotton',
       '80% Viscose, 20% Linen', '100% Acetate',
       '94% Polyamide, 6% Elastane',
       '55.1% Polyester, 39.2% Polyamide, 5.7% Spandex',
       '80.4% Viscose, 14.6% Polyamide, 5% Spandex',
       '70% Polyester, 30% Viscose',
       '62% Viscose, 30% Polyamide, 8% Elastane',
       '90% Viscose, 10% Elastane', '100.0% Cotton',
       '44% Viscose, 28% Nylon, 28% Polyester',
       '65% Polyester, 35% Nylon',
       '72% Acetate, 25% Polyamide, 3% Spandex',
       '62% Rayon, 33% Polyamide, 5% Spandex', '70% Viscose, 30% Linen',
       '50% Viscose, 25% Nylon, 25% Polyester',
       '88% Polyester, 12% Viscose',
       '70% Polyester, 23% Viscose, 7% Elastane',
       '70% Polyester, 20% Rayon, 10% Elastane',
       '62% Viscose, 38% Polyester', '95.0% Polyester, 5.0% Elastane',
       '87% Polyester, 13% Elastane',
       '68% Polyester, 28% Viscose, 4% Spandex',
       '43% Linen, 41% Viscose, 16% Polyester',
       '82% Cotton, 18% Polyester', '80% Polyester, 20% Cotton',
       '68% Polyester, 32% Viscose',
       '66% Polyester, 29% Viscose, 5% Elastane',
       '95% Viscose, 5% Elastane', '90% Polyester, 10% Spandex',
       '98% Lyocell, 2% Polyamide', '93.4% Polyester, 6.6% Spandex',
       '60% Linen, 40% Polyester',
       '78% Polyester, 17% Viscose, 5% Elastane',
       '52% Acrylic, 27% Nylon, 21% Polyester',
       '46% Acrylic, 28% Polyester, 26% Polyamide',
       '65% Viscose, 35% Polyamide', '85% Viscose, 15% Nylon',
       '40% Polyester, 30% Acrylic, 20% Polyamide, 10% Wool',
       '46% Polyester, 32% Polyamide, 21% Viscose, 1% Elastane',
       '70% Viscose, 30% Polyester',
       '64% Acrylic, 26% Elastane, 10% Polyamide',
       '75% Viscose, 25% Polyester', '96% Polyester, 4% Spandex',
       '90.00% Viscose, 10.00% Elastane', '70% Viscose, 30% Polyamide',
       '85% Viscose, 15% Polyester', '94% Viscose, 6% Polyamide',
       '65% Rayon, 30% Polyamide, 5% Elastane',
       '77% Viscose, 20% Polyamide, 3% Elastane',
       '87% Viscose, 13% Polyester',
       '55% Viscose, 27% Polyester, 18% Polyamide',
       '48% Acrylic, 28.3% Polyester, 23.7% Polyamide',
       '70% Acrylic, 18% Polyamide, 8% Wool, 4% Elastane',
       '98% Polyester, 2% Spandex',
       '35% Spandex, 30% Polyester, 20% Mohair, 15% Wool',
       '89% Viscose, 11% Polyamide', '60% Polyester, 40% Cotton',
       '64% Polyamide, 31% Metallized Fibres, 5% Elastane',
       '66% Polyester, 31% Viscose, 3% Elastane',
       '62% Polyester, 34% Cotton, 4% Elastane',
       '79% Polyamide, 17% Metallized Fibres, 4% Elastane',
       '52% Polyester, 28% Viscose, 20% Polyamide',
       '81% Cotton, 13% Viscose, 6% Polyester',
       '60% Cotton, 40% Polyester',
       '70% Polyester, 26% Viscose, 4% Elastane',
       '80% Viscose, 20% Polyester',
       '80% Polyamide, 14% Metallized Fibres, 6% Elastane',
       '50% Cotton, 50% Viscose', '100% Nylon',
       '94% Viscose, 6% Polyester',
       '65% Cotton, 33% Polyester, 2% Elastane',
       '88% Viscose, 12% Polyamide',
       '69% Viscose, 26% Polyamide, 5% Elastane',
       '77.4% Polyester, 19.1% Nylon, 3.5% Spandex',
       '73% Polyester, 21% Viscose, 6% Elastane',
       '45% Viscose, 28% Spandex, 27% Nylon',
       '88% Polyamide, 12% Elastane', '60% Acrylic, 40% Polyamide',
       '83% Polyester, 12% Metallized Fibres, 5% Elastane',
       '85% Viscose, 15% Polyamide', '80% Polyester, 20% Wool',
       '43% Viscose, 32% Polyamide, 25% Polyester',
       '60% Polyurethane, 40% Polyester', '80% Polyester, 20% Acrylic',
       '84% Polyamide, 16% Elastane',
       '67% Polyester, 28% Viscose, 5% Elastane',
       '50% Acrylic, 30% Viscose, 20% Polyester',
       '67% Polyester, 21% Acrylic, 8% Polyamide, 4% Wool',
       '70% Cotton, 30% Linen', '80% Acrylic, 20% Polyester',
       '60% Polyester, 40% Polyurethane', '86% Viscose, 14% Linen',
       '99% Polyester, 1% Elastane', '90% Spandex, 10% Elastane',
       '66.7% Viscose, 33.3% Polyester', '75% Acrylic, 25% Polyamide',
       '72% Viscose, 25% Polyamide, 3% Elastane',
       '50% Viscose, 30% Nylon, 20% Polyester',
       '90% Polyamide, 10% Polyester', '85% Lyocell, 15% Elastane',
       '65% Cotton, 30% Viscose, 5% Linen', '84% Viscose, 16% Linen',
       '83% Polyester, 17% Rayon',
       '65% Polyester, 30% Metallized Fibres, 5% Elastane',
       '80% Polyester, 15% Metallized Fibres, 5% Elastane',
       '72% Polyester, 28% Elastane',
       '73% Cotton, 18% Polyester, 9% Viscose',
       '89% Cotton, 6% Polyester, 5% Viscose',
       '86% Polyester, 14% Viscose',
       '50% Viscose, 27% Polyester, 23% Polyamide',
       '60% Polyester, 35% Viscose, 5% Elastane',
       '50% Viscose, 30% Polyamide, 20% Polyester',
       '82% Nylon, 18% Spandex',
       '48% Polyester, 41% Viscose, 5% Polyamide, 4% Acrylic, 2% Wool',
       '68% Polyester, 24% Polyamide, 8% Elastane',
       '65% Polyester, 35% Cotton', '95.00% Polyester, 5.00% Elastane',
       '70% Polyamide, 30% Metallized Fibres',
       '70% Polyester, 27% Polyamide, 3% Spandex',
       '78% Viscose, 22% Polyamide',
       '70% Viscose, 25% Polyester, 5% Elastane',
       '69% Viscose, 23% Polyamide, 8% Elastane',
       '87% Viscose, 13% Linen',
       '75% Polyester, 18% Viscose, 7% Elastane',
       '82% Polyester, 18% Viscose', '97% Polyamide, 3% Elastane',
       '50% Polyurethane, 48% Polyester, 2% Elastane',
       '85% Cotton, 15% Polyester', '100% Linen',
       '88% Polyester, 10% Viscose, 2% Elastane',
       '67% Polyester, 29% Viscose, 4% Polyamide',
       '67% Polyester, 29% Rayon, 4% Elastane',
       '72% Rayon, 25% Polyamide, 3% Spandex',
       '57% Polyester, 40% Viscose, 3% Elastane',
       '68.6% Viscose, 21.2% Polyester, 10.2% Elastane',
       '55% Viscose, 42% Polyester, 3% Elastane',
       '91% Viscose, 9% Polyester', '87.2% Polyamide, 12.8% Spandex',
       '77% Polyester, 20% Viscose, 3% Elastane',
       '95% Elastane, 5% Polyester',
       '62% Polyester, 33.5% Viscose, 4.5% Elastane',
       '40% Acrylic, 40% Polyester, 20% Viscose',
       '75% Polyester, 19% Viscose, 6% Elastane',
       '50% Acrylic, 50% Polyamide',
       '72% Rayon, 25% Polyamide, 3% Elastane',
       '96% Viscose, 4% Elastane',
       '80% Viscose, 17% Polyester, 3% Elastane',
       '86% Polyester, 14% Elastane', '89% Viscose, 11% Nylon',
       '49% Rayon, 34% Polyester, 17% Polyamide',
       '51% Polyester, 36% Viscose, 13% Polyamide',
       '65% Rayon, 30% Polyamide, 5% Spandex',
       '65% Polyester, 30% Viscose, 5% Elastane',
       '42% Acrylic, 30% Polyester, 28% Polyamide',
       '87% Viscose, 13% Elastane', '53% Polyamide, 47% Viscose',
       '99% Polyester, 1% Spandex',
       '70% Polyester, 27% Polyamide, 3% Elastane',
       '67% Polyester, 33% Viscose',
       '60% Rayon, 37.5% Polyester, 2.5% Spandex',
       '60% Viscose, 33.6% Polyamide, 6.4% Elastane',
       '80% Viscose, 20% Elastane',
       '45% Acrylic, 28% Polyamide, 27% Polyester',
       '94% Polyester, 6% Viscose', '55% Linen, 45% Viscose',
       '42% Viscose, 30% Nylon, 28% Polyamide',
       '67% Polyester, 29% Viscose, 4% Elastane',
       '75% Polyamide, 25% Elastane', '86% Polyamide, 14% Elastane',
       '65% Polyester, 31% Cotton, 4% Elastane',
       '65% Viscose, 35% Lyocell', '93% Cotton, 7% Elastane',
       '65% Polyester, 32% Cotton, 2% Viscose, 1% Lyocell',
       '65% Polyester, 31% Modal, 4% Elastane',
       '88% Polyester, 12% Spandex', '94.6% Polyester, 5.4% Elastane',
       '78% Polyester, 22% Viscose', '67% Polyester, 33% Cotton',
       '77% Viscose, 21% Polyamide, 2% Elastane',
       '45% Polyamide, 45% Viscose, 10% Polyester',
       '84% Polyester, 13% Viscose, 3% Elastane', '97% Rayon, 3% Spandex',
       '90% Polyester, 10% Viscose', '76% Cotton, 24% Viscose',
       '65% Polyamide, 35% Metallized Fibres',
       '49% Viscose, 28% Polyester, 23% Nylon',
       '92% Viscose, 8% Elastane',
       '76% Polyester, 22% Viscose, 2% Elastane',
       '91% Polyamide, 9% Elastane',
       '57% Viscose, 38% Polyamide, 5% Elastane',
       '77% Viscose, 23% Polyamide', '50% Cotton, 45% Viscose, 5% Linen',
       '97.5% Polyester, 2.5% Elastane',
       '68% Polyester, 29% Viscose, 3% Elastane',
       '98% Polyester, 2% Polyamide',
       '84% Polyester, 11% Viscose, 5% Elastane'], dtype=object)

In [32]:
#number of words in 'name' column distribution 
shein_data['name_word_count'] = shein_data['name'].apply(lambda x: len(str(x).split()))
shein_data['name_word_count'].describe()

count    5000.000000
mean        6.949600
std         1.947567
min         3.000000
25%         5.000000
50%         7.000000
75%         8.000000
max        18.000000
Name: name_word_count, dtype: float64

In [31]:
#most common key words
all_words = shein_data['name'].dropna().apply(lambda x: re.findall(r'\b\w+\b', x.lower()))
flat_words = [word for sublist in all_words for word in sublist]
word_freq = Counter(flat_words)

most_common_words = word_freq.most_common(20)
print(most_common_words)

[('shein', 1653), ('skirt', 1223), ('print', 1095), ('pants', 807), ('waist', 771), ('bikini', 766), ('swimsuit', 731), ('hem', 636), ('face', 602), ('covering', 600), ('floral', 534), ('triangle', 523), ('x', 522), ('high', 517), ('leg', 508), ('chain', 501), ('solid', 468), ('halter', 454), ('shorts', 393), ('tie', 393)]